version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"  # MQTT port
    networks:
      - mqtt_network
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db  # Persistence volume for MongoDB data
    ports:
      - "27017:27017"  # MongoDB port
    networks:
      - mqtt_network
    restart: always

  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"  # Node-RED UI port
    networks:
      - mqtt_network
    volumes:
      - nodered_data:/data  # Persistence volume for Node-RED data and configuration
    restart: always

networks:
  mqtt_network:

volumes:
  mongodb_data:
  nodered_data:
