version: '3'
services:
  mosquitto:
    build: ./eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"  # MQTT port
    volumes:
      - mosquitto_config:/mosquitto/config # Persistence volume for mosquitto data
      - mosquitto_data:/mosquitto/data
      - ./certs:/certs:rZ
    networks:
      - mqtt_network
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db  # Persistence volume for MongoDB data
      - ./certs:/certs:rZ
    ports:
      - "27017:27017"  # MongoDB port
    networks:
      - mqtt_network
    restart: always

  nodered:
    build: ./node-red
    container_name: nodered
    ports:
      - "1880:1880"  # Node-RED UI port
    networks:
      - mqtt_network
    volumes:
      - nodered_data:/data  # Persistence volume for Node-RED data and configuration
      - ./certs:/certs:rZ
    restart: always

  omgwtfssl:
    image: paulczar/omgwtfssl
    volumes:
      - ./certs:/certs:Z
    environment:
      - SSL_SUBJECT=mqtt.local

networks:
  mqtt_network:

volumes:
  mongodb_data:
  nodered_data:
  mosquitto_config:
  mosquitto_data:
