version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "8883:8883"  # MQTT port
    volumes:
      - ./mosquitto_config:/mosquitto/config # Persistence volume for mosquitto data
      - mosquitto_data:/mosquitto/data:Z 
      - ./certs:/certs:rZ
    networks:
      - mqtt_network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: loc
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - mongodb_data:/data/db:Z   # Persistence volume for MongoDB data
      - ./certs:/certs:rZ
    ports:
      - "27017:27017"  # MongoDB port
    networks:
      - mqtt_network
    restart: always

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"  # Node-RED UI port
    networks:
      - mqtt_network
    volumes:
      - ./nodered_settings/settings.js:/data/settings.js
      - nodered_data:/data:Z  # Persistence volume for Node-RED data and configuration
      - ./certs:/certs:rZ
    restart: always

  omgwtfssl:
    image: paulczar/omgwtfssl
    volumes:
      - ./certs:/certs:Z
    environment:
      - SSL_SUBJECT=mqtt.local

networks:
  mqtt_network:

volumes:
  mongodb_data:
  nodered_data:
  mosquitto_data:
